import Head from 'next/head';
import { BsCodeSlash, BsFillMoonStarsFill, BsFillSunFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillInstagram, AiFillTwitterCircle } from 'react-icons/ai';
import { MdOutlineWavingHand } from 'react-icons/md';
import Image from "next/image";
import profilePic from '../public/pedrolucas-profile-pic.jpg';
import model3d from '../public/3d.png';
import design from '../public/design-test.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Pedro Lucas Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='
      bg-white dark:bg-gray-900 
      px-4 sm:px-4 md:px-8 lg:px-60
      transition-all duration-500'>

        <section className='min-h-screen'>
          <nav className='py-10 mb-6 flex justify-between items-center'>
            <h1 className='text- font-worksans dark:text-gray-50'>@pedrolucaslco</h1>
            <ul className='flex items-center'>
              <li>
                <a className=' text-slate-400 py-2 rounded-full mr-8 transition-all duration-1000 hover:shadow-lg hover:text-slate-100' href="https://github.com/pedrolucaslcosta" target="_blank">
                  Github
                </a>
              </li>
              <li>

                {darkMode ? (
                  <BsFillSunFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl text-slate-700 dark:text-slate-50 dark:hover:text-slate-400 hover:text-slate-500 transition-all duration-500 hover:animate-spin' />
                ) :
                  (
                    <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl text-slate-700 dark:text-slate-50 dark:hover:text-slate-400 hover:text-slate-500 transition-all duration-500 hover:animate-pulse' />
                  )}

              </li>

              <li>
                <a className='bg-gradient-to-r from-sky-600 to-sky-700 text-white px-5 py-2 rounded-full ml-8 transition-all duration-1000 hover:shadow-lg' href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className='grid grid-cols-3 gap-4'>

            <div className=' 
            col-span-3 lg:col-span-2 md:col-span-2 sm:col-span-3
            bg-gradient-to-tr from-slate-100 via-slate-50 to-sky-100
            dark:bg-gradient-to-tr dark:from-slate-800 dark:via-slate-800 dark:to-slate-700 dark:border-slate-600
            rounded-2xl lg:p-10 p-8
            '>
              <h2 className='text-5xl font-semibold text-slate-900 dark:text-slate-200'>Hello, I'm Pedro.</h2>
              <h3 className='text-2xl py-2 text-slate-500 dark:text-gray-400'>Developer and designer.</h3>
              <p className='text-md py-5 text-gray-500 dark:text-gray-400'>
                A frontend software developer and graphic designer <br/> with 2 years of experience.
              </p>
              <div className='text-xl flex justify-start gap-4 text-slate-500 dark:text-slate-500'>
                <a href='mailto:pedrolucaslcosta@gmail.com' target='_blank' className='text-base font-medium rounded-full bg-gradient-to-r from-slate-800 to-slate-700 text-slate-200 flex items-center px-5 dark:bg-gradient-to-r dark:from-slate-700 dark:to-slate-600'>
                  Contact me
                </a>
                <a href='https://www.instagram.com/pedrolucaslco' target='_blank' className='bg-slate-200 p-3 rounded-full dark:bg-slate-700'>
                  <AiFillInstagram />
                </a>
                <a href='https://www.linkedin.com/in/pedrolucaslcosta' target='_blank' className='bg-slate-200 p-3 rounded-full dark:bg-slate-700'>
                  <AiFillLinkedin />
                </a>
                <a href='https://www.twitter.com/pedrolucaslco' target='_blank' className='bg-slate-200 p-3 rounded-full dark:bg-slate-700'>
                  <AiFillTwitterCircle />
                </a>
              </div>
            </div>

            <div className='
            col-span-3 lg:col-span-1 md:col-span-1 order-first sm:order-first md:order-2 h-64 sm:h-96
            rounded-3xl'>
              <Image className='rounded-2xl h-full w-full object-scale-down sm:object-scale-down md:object-cover bg-slate-500' src={model3d} />
            </div>

            
          </div>

          <div className='p-10 mt-4 rounded-2xl
          bg-gradient-to-tr from-slate-100 via-slate-50 to-sky-100
          dark:bg-gradient-to-r dark:from-sky-900
          dark:via-sky-800 dark:to-sky-600 dark:border-slate-600
          '>
            <h3 className='text-3xl py-1 text-center font-bold dark:text-slate-300'>Projects</h3>
            <p className='text-md py-2 leading-8 text-slate-400 text-center'>
              Coming soon.
            </p>
          </div>

          <div>
            
          </div>
        
        </section>

      </main>
    </div>
  )
}
